spring.application.name=agriserve
server.port=8081


spring.datasource.url=jdbc:mysql://localhost:3306/agriserve

spring.datasource.username=root
spring.datasource.password=22311A0511


spring.jpa.hibernate.ddl-auto=update

# 4. Show SQL in Console (Very helpful for debugging Ravi's sessions!)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 5. MySQL Dialect
#spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect