package com.cognizant.agriserve.service.impl;

import com.cognizant.agriserve.dao.AuditLogRepository;
import com.cognizant.agriserve.dto.AuditLogResponseDTO;
import com.cognizant.agriserve.entity.AuditLog;
import com.cognizant.agriserve.entity.User;
import com.cognizant.agriserve.exception.AuditLogNotFoundException;
import com.cognizant.agriserve.service.AuditLogService;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.modelmapper.ModelMapper;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDateTime;
import java.util.List;
import java.util.stream.Collectors;

@Slf4j

@Service
@RequiredArgsConstructor

public class AuditLogServiceImpl implements AuditLogService {

    private final AuditLogRepository auditLogRepository;
    private final ModelMapper modelMapper;

    @Override
    @Transactional

    public void logAction(User user, String action, String resource) {

        log.info("Recording Audit Action: {} | Resource: {} | User: {}", action, resource, user.getEmail());
        AuditLog auditLog = new AuditLog();
        auditLog.setUser(user);
        auditLog.setAction(action);
        auditLog.setResource(resource);
        // The timestamp is automatically generated by @PrePersist in your AuditLog entity
        auditLogRepository.save(auditLog);

    }

    @Override

    public AuditLogResponseDTO getAuditLogById(Integer auditId) {

        log.debug("Fetching audit log with ID: {}", auditId);
        AuditLog auditLog = auditLogRepository.findById(auditId)
                .orElseThrow(() -> new AuditLogNotFoundException("Audit log not found with ID: " + auditId));
        return mapToDTO(auditLog);

    }

    @Override

    public List<AuditLogResponseDTO> getAllAuditLogs() {

        log.debug("Fetching all audit logs");
        return auditLogRepository.findAll().stream()
                .map(this::mapToDTO)
                .collect(Collectors.toList());

    }

    @Override

    public List<AuditLogResponseDTO> getAuditLogsByUser(User user) {

        log.debug("Fetching audit logs for user ID: {}", user.getUserId());
        return auditLogRepository.findByUser(user).stream()
                .map(this::mapToDTO)
                .collect(Collectors.toList());

    }

    @Override

    public List<AuditLogResponseDTO> getAuditLogsByAction(String action) {

        log.debug("Fetching audit logs for action: {}", action);
        return auditLogRepository.findByAction(action).stream()
                .map(this::mapToDTO)
                .collect(Collectors.toList());

    }

    @Override

    public List<AuditLogResponseDTO> getAuditLogsByResource(String resource) {

        log.debug("Fetching audit logs for resource: {}", resource);
        return auditLogRepository.findByResource(resource).stream()
                .map(this::mapToDTO)
                .collect(Collectors.toList());

    }

    @Override

    public List<AuditLogResponseDTO> getAuditLogsByDateRange(LocalDateTime startTime, LocalDateTime endTime) {

        log.debug("Fetching audit logs between {} and {}", startTime, endTime);
        return auditLogRepository.findByTimestampBetween(startTime, endTime).stream()
                .map(this::mapToDTO)
                .collect(Collectors.toList());

    }

    @Override

    public List<AuditLogResponseDTO> getAuditLogsByUserAndDateRange(User user, LocalDateTime startTime, LocalDateTime endTime) {

        log.debug("Fetching audit logs for user ID: {} between {} and {}", user.getUserId(), startTime, endTime);
        return auditLogRepository.findByUserAndTimestampBetween(user, startTime, endTime).stream()
                .map(this::mapToDTO)
                .collect(Collectors.toList());

    }


    private AuditLogResponseDTO mapToDTO(AuditLog auditLog) {

        AuditLogResponseDTO dto = modelMapper.map(auditLog, AuditLogResponseDTO.class);

        // Manually map nested user fields to ensure they populate correctly in the flat DTO
        if (auditLog.getUser() != null) {
            dto.setUserName(auditLog.getUser().getName());
//            dto.setUserEmail(auditLog.getUser().getEmail());

        }

        return dto;

    }

}
